#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

brew update
brew tap caskroom/cask

# TODO: Ensure both Brew and Caskroom are set up.
if [ "$(which java)" == "" ]; then
  echo "ERROR: Install JDK first.  Maybe use 'brew cask install java'.  Leaving this to you in case you want to handle this differently."
  exit 1
fi

if [ "$(which ant)" == "" ]; then brew install ant; fi
if [ "$(which android)" == "" ]; then
  brew cask install android-sdk
fi

echo y | android update sdk --all --no-ui --filter 'tools,platform-tools'
echo y | android update sdk --all --no-ui --filter 'android-23'
echo y | android update sdk --all --no-ui --filter 'build-tools-23.0.2'
echo y | android update sdk --all --no-ui --filter 'extra-google-m2repository'
echo y | android update sdk --all --no-ui --filter 'extra-android-m2repository'

if [ "$(which aws)" == "" ]; then brew install awscli; fi

# TODO: Use Homebrew, once the checksums are updated...
# brew install homebrew/binary/adobe-air-sdk[-flex]
if [ ! -e air-sdk/bin/compc ]; then
  curl 'https://airdownload.adobe.com/air/mac/download/latest/AIRSDK_Compiler.tbz2' > air-sdk/AIRSDK_Compiler.tbz2
  (
    cd air-sdk
    tar xzf AIRSDK_Compiler.tbz2
  )
fi
