#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

brew update
brew tap caskroom/cask

# TODO: Ensure both Brew and Caskroom are set up.
if [ "$(which java)" == "" ]; then
  echo "ERROR: Install JDK first.  Maybe use 'brew cask install java'.  Leaving this to you in case you want to handle this differently."
  exit 1
fi

if [ "$(which ant)" == "" ]; then brew install ant; fi
if [ "$(which android)" == "" ]; then
  brew cask uninstall android-sdk
  brew cask install android-sdk
fi

ANDROID_HOME=/usr/local/share/android-sdk
export ANDROID_HOME

sdkmanager "build-tools;23.0.2"
sdkmanager "platforms;android-23"
sdkmanager "extras;google;m2repository"
sdkmanager "extras;android;m2repository"

if [ "$(which aws)" == "" ]; then brew install awscli; fi

if [ "$(which compc)" == "" ]; then
  brew cask install adobe-air-sdk
fi
