version: 2.1

orbs:
  teak: teak/sdk-utils@0.0.3

jobs:
  build:
    macos:
      xcode: "10.2.1"
    shell: /bin/bash --login -eo pipefail
    environment:
      ADOBE_AIR_HOME: ~/adobe-air-sdk
    steps:
      - checkout
      - restore_cache:
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.HOMEBREW_VERSION }}
      - run:
          name: Check Homebrew Version
          command: |
            echo "Checking for Homebrew version $HOMEBREW_VERSION"
            [ `brew --version | sed -n 1p | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'` = $HOMEBREW_VERSION ] || brew update
      - run:
          name: Homebrew Depenendcies
          command: HOMEBREW_NO_AUTO_UPDATE=1 ./setup
      - run:
          shell: /bin/bash -eo pipefail
          name: Setup RVM
          command: |
            unset GEM_HOME
            source /Users/distiller/.rvm/scripts/rvm
            rvm autolibs enable
            rvm list | grep 2.4 || rvm install ruby-2.4
            rvm use default
      - run:
          name: AIR SDK
          command: rake sdk:setup
      - save_cache:
          paths:
            - /usr/local/Homebrew/
            - ~/Library/Caches/Homebrew
            - vendor/bundle
            - ~/adobe-air-sdk
            - ~/.rvm
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.HOMEBREW_VERSION }}
      - run:
          name: Build Teak SDK
          command: ./compile
      - persist_to_workspace:
          root: bin/
          paths:
            - io.teak.sdk.Teak.ane
      - run:
          name: ReadTheDocs.org Unified Docs
          command: curl -X POST -d "branches=master" -d "token=$RTD_TOKEN" https://readthedocs.org/api/v2/webhook/teak/41148/
  deploy_versioned:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: bin/
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp bin/io.teak.sdk.Teak.ane s3://teak-build-artifacts/air/io.teak.sdk.Teak-$(git describe --tags --always).ane --acl public-read
      # - run:
      #     name: Trigger Cleanroom Build
      #     command: bundle exec rake build:cleanroom
  deploy_latest:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: bin/
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp bin/io.teak.sdk.Teak.ane s3://teak-build-artifacts/air/io.teak.sdk.Teak.ane --acl public-read
workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_versioned:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_latest:
          requires:
            - hold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
