version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    shell: /bin/bash --login -eo pipefail
    environment:
      ADOBE_AIR_HOME: /usr/local/share/adobe-air-sdk
    steps:
      - checkout
      - restore_cache:
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Fix 'Homebrew must be run under Ruby 2.3!'
          command: brew update
      - run:
          name: Homebrew Depenendcies
          command: ./setup
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ~/Library/Caches/Homebrew/
            - vendor/bundle
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Teak SDK
          command: ./compile
      - persist_to_workspace:
          root: bin/
          paths:
            - io.teak.sdk.Teak.ane
  deploy:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: bin/
      - run:
          name: Upload SDK to S3
          command: |
            aws s3 cp bin/io.teak.sdk.Teak.ane s3://teak-build-artifacts/air/io.teak.sdk.Teak-$(git describe --tags --always).ane --acl public-read --dryrun
            aws s3 cp bin/io.teak.sdk.Teak.ane s3://teak-build-artifacts/air/io.teak.sdk.Teak.ane --acl public-read --dryrun
      - run:
          name: Trigger Cleanroom Build
          command: rake build:cleanroom
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   tags:
          #     only: /.*/
          #   branches:
          #     ignore: /.*/
